#!/bin/bash
defaultName=gridwiz
defaultVersion=1.0.0
defaultRelease=1

echo -e "### Rpm Package Config"
echo -n "Package specFile Name(default : $defaultName) : "
read packageName

if [ -z $packageName ]
then
packageName=$defaultName
fi


echo -n "Package specFIle Version(default : $defaultVersion) : "
read packageVersion

if [ -z $packageVersion ]
then
packageVersion=$defaultVersion
fi

echo -n "Pacakge specFIle Release(default : $defaultRelease) : "
read packageRelease

if [ -z $packageRelease ]
then
packageRelese=$defaultRelease
fi

fullName=$packageName'-'$packageVersion
echo $fullName

mkdir -p ~/rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}


tar czvf $fullName.tar.gz $fullName

cp $packageName.spec ~/rpmbuild/SPECS
cp $fullName.tar.gz ~/rpmbuild/SOURCES

mkdir -p /usr/local/gridwiz
mkdir -p /usr/local/gridwiz/bin
mkdir -p /usr/local/gridwiz/log
mkdir -p /usr/local/gridwiz/config

rpmbuild -ba ~/rpmbuild/SPECS/$packageName.spec
rpm -Uvh ~/rpmbuild/RPMS/x86_64/$fullName-$defaultRelease.x86_64.rpm

