#!/bin/bash
osId=$(lsb_release -i)
osId=$(echo $osId | cut -d: -f2)

defaultName=gridwiz
defaultVersion=1.0.0
defaultRelease=1

echo "### Rpm Package Config"
echo -n "Package specFile Name(default : $defaultName) : "
read packageName

if [ -z $packageName ]
then
packageName=$defaultName 
fi


echo -n "Package specFile Version(default : $defaultVersion) : "
read packageVersion

if [ -z $packageVersion ]
then
packageVersion=$defaultVersion
fi

echo -n "Pacakge specFile Release(default : $defaultRelease) : "
read packageRelease

if [ -z $packageRelease ]
then
packageRelese=$defaultRelease
fi


if [ $osId = CentOS ]
then
path=$(rpm -qa $packageName)
else
path=$(dpkg --get-selections | grep $packageName)
path=${path%" "}

fi
echo $path

if [ -z "$path" ]
then
  echo "Install"
else
  while true; do
    read -p "Package already exist. Install new Package? [y/n] " ans
    case $ans in
    [Yy]* )
    if [ $osId = CentOS ]
    then
      rpm -e $path
    else
      dpkg -r $packageName;
    fi
    echo "Package was removed";
    break;;
    [Nn]* ) exit;;
    * ) echo "Press answer y or n";; 
  esac
done
fi


fullName=$packageName'-'$packageVersion
echo $fullName

sudo mkdir -p ~/rpmbuild/BUILD
sudo mkdir -p ~/rpmbuild/BUILDROOT
sudo mkdir -p ~/rpmbuild/RPMS
sudo mkdir -p ~/rpmbuild/SOURCES
sudo mkdir -p ~/rpmbuild/SPECS
sudo mkdir -p ~/rpmbuild/SRPMS


sudo tar czvf $fullName.tar.gz $fullName

sudo cp $packageName.spec ~/rpmbuild/SPECS
sudo cp $fullName.tar.gz ~/rpmbuild/SOURCES

sudo mkdir -p /usr/local/gridwiz
sudo mkdir -p /usr/local/gridwiz/bin
sudo mkdir -p /usr/local/gridwiz/log
sudo mkdir -p /usr/local/gridwiz/config

rpmbuild -ba ~/rpmbuild/SPECS/$packageName.spec



if [ $osId = CentOS ]
then
  echo "CentOs Install"
  rpm -Uvh ~/rpmbuild/RPMS/x86_64/$fullName-$defaultRelease.x86_64.rpm
else
  echo "Ubuntu Install"
  sh install_debian
fi
