#!/bin/bash

osId=$(lsb_release -i)
osId=$(echo $osId | cut -d: -f2)

defaultName=gridwiz
defaultVersion=1.0.0
defaultRelease=1

echo "### Rpm Package Config"
echo -n "Package specFile Name(default : $defaultName) : "
read packageName

if [ -z $packageName ]
then
packageName=$defaultName
fi 


echo -n "Package specFile Version(default : $defaultVersion) : "
read packageVersion

if [ -z $packageVersion ]
then
packageVersion=$defaultVersion
fi

echo -n "Pacakge specFile Release(default : $defaultRelease) : "
read packageRelease

if [ -z $packageRelease ]
then
packageRelese=$defaultRelease
fi

if [ $osId = CentOS ]
then
path=$(rpm -qa $packageName)
else
path=$(dpkg --get-selections | grep $packageName)
path=${path%" "}
fi


if [ -z "$path" ]
then
  echo "The Package does not exist."
  exit
fi

while true; do
read -p "Uninstall Package [y/n] " ans

case $ans in
  [Yy]* )
  if [ $osId = CentOS ]
  then
  rpm -e $path;
  else
  dpkg -r $path
  fi
  rm -rf /usr/local/bin/config
  rm -rf /usr/local/gridwiz
  rm -rf ~/rpmbuild
  rm -rf ~/rpmbuild_debian

  echo "The Pacakge was removed";
  break;;
  [Nn]* ) exit;;
  * ) echo "Press answer y or n";; 
  esac
done

